### ISSUE TITLE
How did source map generate?

### ISSUE THREAD

**Issue by mr-pinzhang** [microsoft/TypeScript-Babel-Starter#12]
I intend to use this solutions to generate code in my project, including `js` and `ts` files,
but I want to generate `sourceMap` of `ts` files,
how can I achieve that in this example?

**Comment by DanielRosenwasser** [comment]
Good question! You can have Babel generate source-maps using `--source-maps inline` with Babel CLI. We should add this.

**Comment by mr-pinzhang** [comment]
@DanielRosenwasser thanks, expecting your example then.
