### ISSUE TITLE
Update README.md file for webpack setup as babel-loader is not compatible with babel7 

### ISSUE THREAD

**Issue by muditsaurabh** [microsoft/TypeScript-Babel-Starter#3]
Problem
npm run bundle gives following
Error: Cannot find module 'babel-core'

Solution
webpack 3.x | babel-loader 8.x | babel 7.x
npm install babel-loader@8.0.0-beta.0 @babel/core @babel/preset-env webpack
Please refer to https://github.com/babel/babel-loader

**Comment by apepper** [comment]
Already fixed in https://github.com/Microsoft/TypeScript-Babel-Starter/pull/2 => please close.
