### ISSUE TITLE
Supporting eslint

### ISSUE THREAD

**Issue by chetnashah** [microsoft/TypeScript-Babel-Starter#31]
ESLint would expect ESTree compliant input to accurately report ESLint errors. so parser used is `typescript-eslint-parser`.

The eslint command works fine but VSCode stops showing ESLint errors with following config:
```json
{
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "env": {
        "browser": true
    },
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "ecmaVersion": 6,
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "linebreak-style":"off"
    },
    "settings": {
      "import/resolver": "webpack"
    },
    "overrides": [
        {
            "files": ["**/*.ts", "**/*.tsx"],
            "parser": "typescript-eslint-parser",
            "rules": {
              "no-undef": "off",
              "react/prop-types": "off"
            }
        }
    ]
}
```

Repo for reproducibility: https://github.com/chetnashah/formik-app

**Comment by DanielRosenwasser** [comment]
Weird, but that sounds like an issue with the ESLint plugin for VS Code, doesn't it?

**Comment by chetnashah** [comment]
i'll try to dig deeper and get back

**Comment by chetnashah** [comment]
Adding setting for vscode-eslint did the trick.
https://github.com/Microsoft/vscode-eslint/issues/227#issuecomment-297118310
